[book]
title = "基于ARM的Linux操作系统引导详解"
authors = ["刘海"]
language = "zh-cn"
[output.html]
# 引入你的自定义 CSS 文件
# additional-css = ["book.css"]
mathjax-support = true
# 设置默认加载的主题，可选值: "light", "rust", "coal", "navy", "ayu"
default-theme = "light"

# 如果用户系统开启了系统级深色模式，mdBook 会默认切换成 navy。
# 如果你想防止黑色主题出 bug，也可以把它也强制改成浅色，或者改为相对更稳定的 "ayu"
preferred-dark-theme = "light"
theme = "theme"
# 告诉 mdBook 在编译时加载你的自定义 CSS
additional-css = ["theme/custom.css"]
[build]
build-dir = "docs"